In [189]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [190]:
df = pd.read_csv('data/data.csv')

In [191]:
df.head()

Text  Polarity
0            আমাদের সজাগ থাকতে হবে টিকা নেওয়া নিয়ে।          1
1                                  ভ্যাকসিন ভালো না।         0
2                 আমার পরিবারের সকলেই টিকা নিয়েছে।          1
3  টিকা লক্ষণীয় রোগ প্রতিরোধে একইভাবে উচ্চ কার্য...         1
4           অনলাইনে আবেদন করে আমি ভ্যাকসিন নিয়েছি।          1

In [192]:
df_shuffle = df.sample(frac = 1,random_state=42)
df_shuffle.head()

Text  Polarity
1011  কেন্দ্রে প্রচণ্ড ভিড় থাকায় অনেকে ভেক্সিন পায...         0
3182  ভ্যাকসিন দিতে গিয়ে কোনরকম ঝামেলার সম্মুখীন হত...         1
3350  করোনার ভ্যাকসিনগুলি আপনাকে করোনায় অসুস্থ করতে ...         1
897                        ভ্যাকসিন নিয়ে আমি ভালো আছি।         1
2293                               টিকা ছাড়াও ভালো হয়।         0

In [193]:
df['Polarity'].value_counts()

1    2007
0    1800
Name: Polarity, dtype: int64

In [194]:
train_sentence,test_sentence,train_label,test_label = train_test_split(df_shuffle['Text'].to_numpy(),df_shuffle['Polarity'].to_numpy(),test_size=0.2,random_state=42)

In [195]:
train_sentence[:10]

array(['সময় মত ২য় ডোজ নিতে দেরি করলে মানুষ মারা যায়।',
       'টিকা নিতে হবে। টিকে থাকতে হবে এই মহামারীতে।',
       'টিকা নেওয়ার পর আমার জ্বর এসেছিলো। আমি মনে করি যে টিকাটি আমার শরীরের ঠিক কাজ করেছে।',
       'কিছু ধরণের COVID-19 ভ্যাকসিন মেসেঞ্জার RNA (mRNA) ব্যবহার করে তৈরি করা হয়েছে, এটি একটি নতুন প্রযুক্তি যা প্রচলিত পদ্ধতির ভ্যাকসিন তৈরির চেয়ে দ্রুত পদ্ধতির অনুমতি দেয়।',
       'আপনার কাছে যখন বিকল্প উপায়ে থাকে, তখন ভ্যাকসিন নেওয়ার কোনো প্রয়োজন নেই।',
       'ভেকসিনই একমাত্র উপায় নয় আরও অনেক উপায় আছে।',
       'সরকারের পক্ষ থেকে ইউনিয়নভিত্তিক টিকা প্রদানের যে পরিকল্পনা গ্রহণ করা হয়েছে সেখানে অনেক দুর্নীতি হচ্ছে। ',
       'টিকার জন্য নিবন্ধন করেছি কিন্তু আমার এসএমএস আসছে না',
       'আমি বিদেশ যাবো দেখে আগে আগেই টিকা নিয়ে নিছি। ',
       'টিকা গ্রহণের পর দুর্বল হয়ে যায় বা টিকা গ্রহণের পর লোকে মারা যায়, গ্রাম ও প্রত্যন্ত অঞ্চলে এই ধরণের লোকেদের ভুল বিশ্বাস ভাঙা উচিত বলেও জানিয়েছেন।'],
      dtype=object)

In [196]:
# visualize some random training examples

import random

random_index = random.randint(0,len(train_sentence) -5)

for row in df_shuffle[['Text','Polarity']][random_index:random_index+5].itertuples():
    _,text,polarity = row
    print(f"Target:{polarity}", "(Positive FeedBack)" if polarity > 0 else "(Negative FeedBack)")
    print(f"Text\n {text}\n")
    print("---\n")


Target:1 (Positive FeedBack)
Text
 আমার আব্বা আম্মা দুইজনেরই করোনা হইছিলো।তারা পরে টিকা নিছে।

---

Target:0 (Negative FeedBack)
Text
 টিকা নিবো না আমি।

---

Target:1 (Positive FeedBack)
Text
 টিকা নিয়াই তো বাঁইচা আছি।টিকা ছাড়া কি আর বাঁচবার পারতাম। 

---

Target:1 (Positive FeedBack)
Text
 ৬৫ বছরের বেশি বয়সীদের ক্ষেত্রে টিকার  ৯৪ শতাংশ কার্যকর।

---

Target:1 (Positive FeedBack)
Text
 যাদের রোগ প্রতিরোধ ক্ষমতা ভাল শরীরে, তাদেরও টিকা নেয়া জরুরী। কোভিড সংক্রমণ রোধে সবাই ভ্যাক্সিনেটেড হলেই আমরা শঙ্কামুক্ত হবো।

---



In [197]:

len(train_sentence), len(train_label),len(test_sentence),len(test_label)

(3045, 3045, 762, 762)

In [198]:
import tensorflow as tf
from keras.layers.preprocessing.text_vectorization import TextVectorization
import numpy as np

text_vec = TextVectorization()

In [199]:
average_word_per_sentence = round(sum(len(i.split()) for i in train_sentence)/len(train_sentence))

### Settings Parmaeters for TextVectorization




In [200]:
max_vocab_length = 10000
max_length = average_word_per_sentence
text_vectorized = TextVectorization(
    max_tokens=max_vocab_length,
    output_mode='int',
    output_sequence_length=max_length)

In [201]:
text_vectorized.adapt(train_sentence)

In [202]:
sample_sentence = 'সময় মত ২য় ডোজ নিতে দেরি করলে মানুষ মারা যায়।'

text_vectorized([sample_sentence])

<tf.Tensor: shape=(1, 11), dtype=int64, numpy=array([[152, 498, 522,  10,  14, 672, 569,  33, 175, 189,   0]])>

In [203]:

random_sentence = random.choice(train_sentence)
print(f"Original text:\n\n{random_sentence}\n\n Vectorized version : {text_vectorized([random_sentence])}")

Original text:

ভেকসিন কি মানুষ মারার জন্য।

 Vectorized version : [[  29   42   33 1134 1013    0    0    0    0    0    0]]


In [204]:


word_to_vocab = text_vectorized.get_vocabulary()

top_10_word = word_to_vocab[:10]
bottom_10_word = word_to_vocab[-10:]

print(f"Number of words in vocabulary {len(word_to_vocab)}\n")
print(f"Top 10 words : {top_10_word}")
print(f"Bottom 10 words : {bottom_10_word}")

Number of words in vocabulary 5201

Top 10 words : ['', '[UNK]', 'টিকা', 'ভ্যাকসিন', 'আমি', 'না।', 'না', 'করোনা', 'জন্য', 'এবং']
Bottom 10 words : ['c130j', 'astrazenecaএর', '95।', '95', '90', '6', '3', '25', '18', '10']


In [221]:
# making an embedding layer

from keras.layers import Embedding

embedding = Embedding(
    input_dim=max_vocab_length,
    output_dim=128,
    input_length=max_length,
   
)
embedding

In [206]:
random_sentence = random.choice(train_sentence)

print(f" Original Text :\n\n {random_sentence} \n\n Embedding Version : ")
sample_emb = embedding(text_vectorized([random_sentence])) 
sample_emb

 Original Text :

 সম্প্রতি বিকশিত কোভিড-১৯ ভ্যাকসিনের সম্ভাব্যতা উপলব্ধি করতে, চিকিত্সকদের অবশ্যই রোগীদের এবং সম্প্রদায়ের সাথে কার্যকরভাবে কাজ করতে হবে যাতে তারা ব্যাপকভাবে পরিচালনা করতে পারে। 

 Embedding Version : 


<tf.Tensor: shape=(1, 11, 128), dtype=float32, numpy=
array([[[ 0.00051565,  0.02914539,  0.00675245, ...,  0.01728383,
          0.02105465,  0.01731611],
        [ 0.01672076, -0.04900774,  0.0163192 , ..., -0.02764123,
          0.04497671, -0.00768862],
        [-0.03269236,  0.02565442,  0.03640323, ..., -0.00589502,
          0.00695944, -0.04884453],
        ...,
        [-0.0241183 , -0.04309009,  0.01391038, ..., -0.04418991,
         -0.0177781 ,  0.02394113],
        [ 0.04534632,  0.00550866, -0.04174482, ...,  0.02079831,
          0.04747975,  0.00638709],
        [-0.00983083, -0.01394055, -0.04556079, ..., -0.02064484,
         -0.03279734, -0.04134419]]], dtype=float32)>

In [207]:
sample_emb[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.00051565,  0.02914539,  0.00675245, -0.02036275,  0.01523408,
        0.02897325,  0.00225223,  0.03368625, -0.04127864,  0.03400436,
       -0.00960358,  0.01642314,  0.03975615,  0.00669307,  0.01769874,
       -0.02109981,  0.03000016,  0.04673835,  0.04866878, -0.04557038,
        0.02613202, -0.00147577, -0.02890285, -0.04175503, -0.04895945,
       -0.01824268,  0.01056148,  0.02896241, -0.00287686,  0.0197514 ,
        0.03600316, -0.01842361,  0.00825878,  0.0488991 ,  0.0461713 ,
        0.01072968,  0.010236  ,  0.04149039,  0.02354988,  0.02520821,
       -0.04825497,  0.01012561,  0.0342258 , -0.04171243, -0.04266273,
       -0.02998464,  0.04022888, -0.02979335, -0.00058061, -0.03135654,
       -0.00838403, -0.03633987, -0.00777141,  0.01539506,  0.00580326,
        0.03226092,  0.04919148, -0.02114652, -0.04247082, -0.00839585,
       -0.04235336, -0.02334355,  0.03823513, -0.01091648, -0.0439994 ,
       -0.047602

### Model 1 : Naive Bayes Classifier

In [208]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


model_naive_bayes = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('multiNB',MultinomialNB())
])

model_naive_bayes.fit(train_sentence,train_label)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('multiNB', MultinomialNB())])

In [209]:
score = model_naive_bayes.score(test_sentence,test_label)
print(f'Our Naive Bayes accuracy: {score*100:.2f} %')

Our Naive Bayes accuracy: 66.80 %


In [210]:

# Prediction Test

naive_bayes_pred = model_naive_bayes.predict(test_sentence[:5])

naive_bayes_pred[:5], test_label[:5]

(array([0, 0, 0, 1, 0]), array([0, 0, 1, 0, 0]))

In [211]:
model_naive_bayes.predict([test_sentence[1]]),test_label[1]

(array([0]), 0)

In [212]:
rdint = random.randint(0,abs(len(test_sentence) -5))

for i,word in enumerate(test_sentence[rdint:rdint+5]):
  
    print(f"Text: {word}  pred: {model_naive_bayes.predict([word])[0]} original: {test_label[rdint+i+1]}\n\n")

Text: আপনারা সবাই টিকা নেবেন। এটা আপনার কর্তব্য।  pred: 1 original: 0


Text: আমাদের স্কুল থেকে বলা হয়েছে সেখান থেকে টিকা দেওয়ার কোন ব্যবস্থা করা হবে না।   pred: 1 original: 0


Text: এখন ও অনেক মানুষ টিকা না নিয়ে ঘুরে বেরাচ্ছে তাদের কি করবেন?  pred: 0 original: 0


Text: কেন্দ্রে ভেক্সিন কার্যক্রম পরিচালনাকারী কাউকে চোখে পড়েনি।  pred: 0 original: 0


Text: করোনা হলে কোভিড এর টীকা নিব, এখন না।  pred: 0 original: 0




In [213]:
# Calculate Accuracy

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true,y_pred):
    model_accuracy = accuracy_score(y_true,y_pred) *100
    precision,recall,f1,_ = precision_recall_fscore_support(y_true,y_pred,average='weighted')
    model_result = {
        'accuracy':model_accuracy,
        'precision':precision,
        'recall':recall,
        'f1':f1
    }
    return model_result

In [214]:
calculate_results(model_naive_bayes.predict(test_sentence),test_label)

{'accuracy': 66.7979002624672,
 'precision': 0.6960798636606401,
 'recall': 0.6679790026246719,
 'f1': 0.6729967926241313}

In [215]:
import pickle
with open ('models/naive_bayes.pkl', 'wb') as f:
    pickle.dump(model_naive_bayes,f)

In [216]:
class BuildModel():

    def __init__(self,train_sentence,train_label,test_sentence,test_label,algo) -> None:
        self.train_sentence = train_sentence
        self.train_label = train_label
        self.test_sentence = test_sentence
        self.test_label = test_label
        self.algo = algo

    
    def run(self):
        self.build_model()
        self.score()
        return self.calculate_results()

    def build_model(self):
        self.model = Pipeline([
            ('tfidf', TfidfVectorizer()),
            ('algo',algo)
        ])
        return self.model.fit(self.train_sentence,train_label)
    
    def score(self):
        return self.model.score(test_sentence,test_label)

    def calculate_results(self):
        y_true = test_label
        y_pred = self.model.predict(test_sentence)
        model_accuracy = accuracy_score(y_true,y_pred) *100
        precision,recall,f1,_ = precision_recall_fscore_support(y_true,y_pred,average='weighted')
        model_result = {
            'accuracy':model_accuracy,
            'precision':precision,
            'recall':recall,
            'f1':f1
        }
        return model_result

        

In [217]:


naive_bayes_model_run = BuildModel(train_sentence,train_label,test_sentence,test_label,algo=MultinomialNB())
naive_bayes_model_run.run()

{'accuracy': 66.7979002624672,
 'precision': 0.6768599962715631,
 'recall': 0.6679790026246719,
 'f1': 0.6629612126252126}

In [218]:
from sklearn.ensemble import RandomForestClassifier

svc = BuildModel(train_sentence,train_label,test_sentence,test_label,algo=RandomForestClassifier())
svc.run()

{'accuracy': 66.7979002624672,
 'precision': 0.6768599962715631,
 'recall': 0.6679790026246719,
 'f1': 0.6629612126252126}

In [241]:
# Building Neural Network 
import keras as ks
from keras import layers,Model

input = layers.Input(shape=(1,), dtype="string")
x = text_vectorized(input)
x = embedding(x)
x = layers.GlobalAveragePooling1D()(x)
output = layers.Dense(1, activation="sigmoid")(x)
nn_model = Model(input,output)


In [242]:
nn_model.compile(loss='binary_crossentropy',optimizer="Adam",metrics=['accuracy'])

In [243]:
nn_model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_8 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_5 (TextV  (None, 11)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 11, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense_5 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
Non-tra

In [244]:
nn_history = nn_model.fit(train_sentence,train_label, epochs=5)

Epoch 1/5
96/96 [==============================] - 3s 11ms/step - loss: 0.6707 - accuracy: 0.7126
Epoch 2/5
96/96 [==============================] - 1s 13ms/step - loss: 0.5661 - accuracy: 0.8187
Epoch 3/5
96/96 [==============================] - 1s 11ms/step - loss: 0.4463 - accuracy: 0.8502
Epoch 4/5
96/96 [==============================] - 1s 11ms/step - loss: 0.3617 - accuracy: 0.8752
Epoch 5/5
96/96 [==============================] - 1s 11ms/step - loss: 0.3020 - accuracy: 0.8975


In [247]:

nn_pred = tf.squeeze(tf.round(nn_model.predict(test_sentence))) 

24/24 [==============================] - 0s 4ms/step


In [248]:
calculate_results(test_label,nn_pred)

{'accuracy': 77.82152230971128,
 'precision': 0.7842485540551773,
 'recall': 0.7782152230971129,
 'f1': 0.7767896757115735}

In [249]:
nn_model.save('models/nn_model')

INFO:tensorflow:Assets written to: models/nn_model/assets


INFO:tensorflow:Assets written to: models/nn_model/assets
