In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data/data.csv')

In [3]:
df.head()

Text  Polarity
0            আমাদের সজাগ থাকতে হবে টিকা নেওয়া নিয়ে।          1
1                                  ভ্যাকসিন ভালো না।         0
2                 আমার পরিবারের সকলেই টিকা নিয়েছে।          1
3  টিকা লক্ষণীয় রোগ প্রতিরোধে একইভাবে উচ্চ কার্য...         1
4           অনলাইনে আবেদন করে আমি ভ্যাকসিন নিয়েছি।          1

In [4]:
df_shuffle = df.sample(frac = 1,random_state=42)
df_shuffle.head()

Text  Polarity
1011  কেন্দ্রে প্রচণ্ড ভিড় থাকায় অনেকে ভেক্সিন পায...         0
3182  ভ্যাকসিন দিতে গিয়ে কোনরকম ঝামেলার সম্মুখীন হত...         1
3350  করোনার ভ্যাকসিনগুলি আপনাকে করোনায় অসুস্থ করতে ...         1
897                        ভ্যাকসিন নিয়ে আমি ভালো আছি।         1
2293                               টিকা ছাড়াও ভালো হয়।         0

In [5]:
df['Polarity'].value_counts()

1    2007
0    1800
Name: Polarity, dtype: int64

In [6]:
train_sentence,test_sentence,train_label,test_label = train_test_split(df_shuffle['Text'].to_numpy(),df_shuffle['Polarity'].to_numpy(),test_size=0.2,random_state=42)

In [7]:
train_sentence[:10]

array(['সময় মত ২য় ডোজ নিতে দেরি করলে মানুষ মারা যায়।',
       'টিকা নিতে হবে। টিকে থাকতে হবে এই মহামারীতে।',
       'টিকা নেওয়ার পর আমার জ্বর এসেছিলো। আমি মনে করি যে টিকাটি আমার শরীরের ঠিক কাজ করেছে।',
       'কিছু ধরণের COVID-19 ভ্যাকসিন মেসেঞ্জার RNA (mRNA) ব্যবহার করে তৈরি করা হয়েছে, এটি একটি নতুন প্রযুক্তি যা প্রচলিত পদ্ধতির ভ্যাকসিন তৈরির চেয়ে দ্রুত পদ্ধতির অনুমতি দেয়।',
       'আপনার কাছে যখন বিকল্প উপায়ে থাকে, তখন ভ্যাকসিন নেওয়ার কোনো প্রয়োজন নেই।',
       'ভেকসিনই একমাত্র উপায় নয় আরও অনেক উপায় আছে।',
       'সরকারের পক্ষ থেকে ইউনিয়নভিত্তিক টিকা প্রদানের যে পরিকল্পনা গ্রহণ করা হয়েছে সেখানে অনেক দুর্নীতি হচ্ছে। ',
       'টিকার জন্য নিবন্ধন করেছি কিন্তু আমার এসএমএস আসছে না',
       'আমি বিদেশ যাবো দেখে আগে আগেই টিকা নিয়ে নিছি। ',
       'টিকা গ্রহণের পর দুর্বল হয়ে যায় বা টিকা গ্রহণের পর লোকে মারা যায়, গ্রাম ও প্রত্যন্ত অঞ্চলে এই ধরণের লোকেদের ভুল বিশ্বাস ভাঙা উচিত বলেও জানিয়েছেন।'],
      dtype=object)

In [8]:
# visualize some random training examples

import random

random_index = random.randint(0,len(train_sentence) -5)

for row in df_shuffle[['Text','Polarity']][random_index:random_index+5].itertuples():
    _,text,polarity = row
    print(f"Target:{polarity}", "(Positive FeedBack)" if polarity > 0 else "(Negative FeedBack)")
    print(f"Text\n {text}\n")
    print("---\n")


Target:0 (Negative FeedBack)
Text
 ভ্যাকসিন নিলে তো অনেক সমস্যা দেখা দেয়।

---

Target:0 (Negative FeedBack)
Text
 আর কেউ খাচ্ছে না টিকা, তাই বাঙালি কে খাওয়া এখন।

---

Target:0 (Negative FeedBack)
Text
 ভেকসিন এ গরুর রক্ত থাকে।

---

Target:0 (Negative FeedBack)
Text
 কোভিড ভ্যাকসিন সম্পূর্ণ হালাল কিনা তা এখনও গবেষণা করে পাওয়া যায়নি। 

---

Target:1 (Positive FeedBack)
Text
 কেউ যদি প্রথম ডোজ নিয়ে থাকে এবং তার যদি কিছু উপসর্গ দেখা না দেয়, তাহলে নির্দ্বিধায়-নির্ভয়ে দ্বিতীয় ডোজ নিতে হবে।

---



In [9]:

len(train_sentence), len(train_label),len(test_sentence),len(test_label)

(3045, 3045, 762, 762)

In [10]:
import tensorflow as tf
from keras.layers.preprocessing.text_vectorization import TextVectorization
import numpy as np

text_vec = TextVectorization()

2023-02-19 21:43:04.634507: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-19 21:43:05.623478: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-19 21:43:05.624804: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-19 21:43:09.410005: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [11]:
average_word_per_sentence = round(sum(len(i.split()) for i in train_sentence)/len(train_sentence))

### Settings Parmaeters for TextVectorization




In [12]:
max_vocab_length = 10000
max_length = average_word_per_sentence
text_vectorized = TextVectorization(
    max_tokens=max_vocab_length,
    output_mode='int',
    output_sequence_length=max_length)

In [13]:
text_vectorized.adapt(train_sentence)

In [14]:
sample_sentence = 'সময় মত ২য় ডোজ নিতে দেরি করলে মানুষ মারা যায়।'

text_vectorized([sample_sentence])

<tf.Tensor: shape=(1, 11), dtype=int64, numpy=array([[152, 498, 522,  10,  14, 672, 569,  33, 175, 189,   0]])>

In [15]:

random_sentence = random.choice(train_sentence)
print(f"Original text:\n\n{random_sentence}\n\n Vectorized version : {text_vectorized([random_sentence])}")

Original text:

করোনাকে ভয় না পেয়ে সচেতন নাগরিক হিসেবে মাক্স ব্যবহার করুন, ভেক্সিন নিতে হবে না।

 Vectorized version : [[332  89   6 840 319 553 180 728 270 416  39]]


In [16]:


word_to_vocab = text_vectorized.get_vocabulary()

top_10_word = word_to_vocab[:10]
bottom_10_word = word_to_vocab[-10:]

print(f"Number of words in vocabulary {len(word_to_vocab)}\n")
print(f"Top 10 words : {top_10_word}")
print(f"Bottom 10 words : {bottom_10_word}")

Number of words in vocabulary 5201

Top 10 words : ['', '[UNK]', 'টিকা', 'ভ্যাকসিন', 'আমি', 'না।', 'না', 'করোনা', 'জন্য', 'এবং']
Bottom 10 words : ['c130j', 'astrazenecaএর', '95।', '95', '90', '6', '3', '25', '18', '10']


In [17]:
# making an embedding layer

from keras.layers import Embedding

embedding = Embedding(
    input_dim=max_vocab_length,
    output_dim=128,
    input_length=max_length,
   
)
embedding

In [18]:
random_sentence = random.choice(train_sentence)

print(f" Original Text :\n\n {random_sentence} \n\n Embedding Version : ")
sample_emb = embedding(text_vectorized([random_sentence])) 
sample_emb

 Original Text :

 আমি মনে করি টিকা নেওয়া জরুরী এবং উচিত। 

 Embedding Version : 


<tf.Tensor: shape=(1, 11, 128), dtype=float32, numpy=
array([[[ 0.04211397,  0.04096452, -0.03018483, ...,  0.02016247,
          0.00776647,  0.00674547],
        [ 0.01861342,  0.02863599,  0.00116309, ..., -0.0296996 ,
          0.04511601, -0.02943499],
        [ 0.01278445,  0.01401693, -0.00447685, ...,  0.01015432,
          0.01870907,  0.00307056],
        ...,
        [ 0.04439985,  0.04656483,  0.00499258, ...,  0.01102858,
          0.04520801, -0.02584496],
        [ 0.04439985,  0.04656483,  0.00499258, ...,  0.01102858,
          0.04520801, -0.02584496],
        [ 0.04439985,  0.04656483,  0.00499258, ...,  0.01102858,
          0.04520801, -0.02584496]]], dtype=float32)>

In [19]:
sample_emb[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.04211397,  0.04096452, -0.03018483, -0.00186721,  0.04599554,
        0.02457141,  0.02337706,  0.01491535,  0.00303651,  0.04636452,
        0.03826341,  0.00122217, -0.01218275,  0.00072576,  0.0346709 ,
        0.0048288 ,  0.00942798,  0.02333397, -0.01163299, -0.02142945,
       -0.00664592,  0.01013374,  0.00406834,  0.04113383, -0.01086297,
        0.01723566,  0.03294731,  0.0207161 , -0.0263526 ,  0.03751827,
        0.02187902, -0.03216145,  0.02355563, -0.04447166, -0.04998688,
        0.01458291,  0.02732556, -0.03208004, -0.00356527,  0.02390702,
        0.03664713, -0.0189574 , -0.018169  ,  0.02323525, -0.02777487,
       -0.00546936, -0.01256884,  0.0128341 , -0.00848389,  0.02096841,
       -0.01326156,  0.01538217,  0.01885146,  0.0255036 , -0.03469086,
        0.04456017, -0.04695258, -0.02769562,  0.04253255, -0.02338432,
        0.03765735, -0.04828607,  0.04138282, -0.01866494, -0.01895246,
        0.015309

### Model 1 : Naive Bayes Classifier

In [20]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline


model_naive_bayes = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('multiNB',MultinomialNB())
])

model_naive_bayes.fit(train_sentence,train_label)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('multiNB', MultinomialNB())])

In [21]:
score = model_naive_bayes.score(test_sentence,test_label)
print(f'Our Naive Bayes accuracy: {score*100:.2f} %')

Our Naive Bayes accuracy: 66.80 %


In [22]:

# Prediction Test

naive_bayes_pred = model_naive_bayes.predict(test_sentence[:5])

naive_bayes_pred[:5], test_label[:5]

(array([0, 0, 0, 1, 0]), array([0, 0, 1, 0, 0]))

In [23]:
model_naive_bayes.predict([test_sentence[1]]),test_label[1]

(array([0]), 0)

In [24]:
rdint = random.randint(0,abs(len(test_sentence) -5))

for i,word in enumerate(test_sentence[rdint:rdint+5]):
  
    print(f"Text: {word}  pred: {model_naive_bayes.predict([word])[0]} original: {test_label[rdint+i+1]}\n\n")

Text: এত টীকা আসতেছে তাহলে গণ টীকা কার্যক্রম গতিহীন কেন? তবে কি দূর্নীতিবাজরা আবার টীকা বিক্রির পায়তারা করছে?  pred: 1 original: 1


Text: এইবার ছুটিতে বাড়ি গিয়ে আমি টিকা নিব।  pred: 1 original: 1


Text: কোভিডের টিকা আমি তিনটাই সম্পন্ন করেছি।  pred: 1 original: 0


Text: আমিি যুবক মানুষ আমার টিকা লাগে না।  pred: 1 original: 0


Text: আমার অনেক সমস্যা আছে আমি ভ্যাকসিন নিব না।  pred: 0 original: 1




In [25]:
# Calculate Accuracy

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true,y_pred):
    model_accuracy = accuracy_score(y_true,y_pred) *100
    precision,recall,f1,_ = precision_recall_fscore_support(y_true,y_pred,average='weighted')
    model_result = {
        'accuracy':model_accuracy,
        'precision':precision,
        'recall':recall,
        'f1':f1
    }
    return model_result

In [26]:
calculate_results(model_naive_bayes.predict(test_sentence),test_label)

{'accuracy': 66.7979002624672,
 'precision': 0.6960798636606401,
 'recall': 0.6679790026246719,
 'f1': 0.6729967926241313}

In [27]:
import pickle
with open ('models/naive_bayes.pkl', 'wb') as f:
    pickle.dump(model_naive_bayes,f)

In [39]:
def build_model( algorithm, train_sentence=train_sentence, train_label=train_label):
    model_pipeline = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('Algorithum',algorithm)
    ])
    model_pipeline.fit(train_sentence,train_label)
    return model_pipeline
    

### Logistic   Regression

In [41]:
from sklearn.linear_model import LogisticRegression
model_logistic_regression = build_model(LogisticRegression())
model_logistic_regression.score(test_sentence,test_label)
calculate_results(model_logistic_regression.predict(test_sentence),test_label)

{'accuracy': 68.11023622047244,
 'precision': 0.6878497554576837,
 'recall': 0.6811023622047244,
 'f1': 0.6823122073541078}

### Build Model with Random Forest, Gradient Boosting, XGBoost, LightGBM

In [42]:
from sklearn.svm import LinearSVC   
model_linear_svc = build_model(LinearSVC())
model_linear_svc.score(test_sentence,test_label)
calculate_results(model_linear_svc.predict(test_sentence),test_label)

{'accuracy': 66.14173228346458,
 'precision': 0.6624484936730389,
 'recall': 0.6614173228346457,
 'f1': 0.6616414616391161}

In [43]:

from sklearn.ensemble import RandomForestClassifier
model_random_forest = build_model(RandomForestClassifier())
model_random_forest.score(test_sentence,test_label)
calculate_results(model_random_forest.predict(test_sentence),test_label)


{'accuracy': 70.86614173228347,
 'precision': 0.7099220627322717,
 'recall': 0.7086614173228346,
 'f1': 0.7088965103912331}

In [44]:

from sklearn.ensemble import GradientBoostingClassifier
model_gradient_boosting = build_model(GradientBoostingClassifier())
model_gradient_boosting.score(test_sentence,test_label)
calculate_results(model_gradient_boosting.predict(test_sentence),test_label)


{'accuracy': 69.02887139107612,
 'precision': 0.708761254131876,
 'recall': 0.6902887139107612,
 'f1': 0.6933952975370142}

In [45]:

from sklearn.ensemble import AdaBoostClassifier
model_adaboost = build_model(AdaBoostClassifier())
model_adaboost.score(test_sentence,test_label)
calculate_results(model_adaboost.predict(test_sentence),test_label)


{'accuracy': 67.45406824146981,
 'precision': 0.6753414383607161,
 'recall': 0.6745406824146981,
 'f1': 0.6747134648709452}

In [46]:

from sklearn.ensemble import ExtraTreesClassifier
model_extra_tree = build_model(ExtraTreesClassifier())
model_extra_tree.score(test_sentence,test_label)
calculate_results(model_extra_tree.predict(test_sentence),test_label)


{'accuracy': 71.5223097112861,
 'precision': 0.7166157943784878,
 'recall': 0.7152230971128609,
 'f1': 0.7154750142924149}

In [47]:

from sklearn.ensemble import BaggingClassifier
model_bagging = build_model(BaggingClassifier())
model_bagging.score(test_sentence,test_label)
calculate_results(model_bagging.predict(test_sentence),test_label)


{'accuracy': 66.01049868766404,
 'precision': 0.6609413032437741,
 'recall': 0.6601049868766404,
 'f1': 0.6601945618874624}

In [48]:

from sklearn.neighbors import KNeighborsClassifier
model_knn = build_model(KNeighborsClassifier())
model_knn.score(test_sentence,test_label)
calculate_results(model_knn.predict(test_sentence),test_label)


{'accuracy': 56.03674540682415,
 'precision': 0.7169998975592242,
 'recall': 0.5603674540682415,
 'f1': 0.5967490612916128}

In [49]:

from sklearn.tree import DecisionTreeClassifier
model_decision_tree = build_model(DecisionTreeClassifier())
model_decision_tree.score(test_sentence,test_label)
calculate_results(model_decision_tree.predict(test_sentence),test_label)


{'accuracy': 63.25459317585301,
 'precision': 0.6325459317585301,
 'recall': 0.6325459317585301,
 'f1': 0.6325459317585301}

In [50]:
#xgboost
from sklearn.ensemble import GradientBoostingClassifier
model_xgboost = build_model(XGBClassifier())
model_xgboost.score(test_sentence,test_label)
calculate_results(model_xgboost.predict(test_sentence),test_label)

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
# make a function to save model

def save_model(model,filename):
    with open(f'models/{filename}.pkl','wb') as f:
        pickle.dump(model,f)

save_model(model_naive_bayes,'naive_bayes')

In [52]:

# make a function to visualize the model
import matplotlib.pyplot as plt

def visualize_model(model, model_name):
    fig, ax = plt.subplots(figsize=(10, 10))
    plot_confusion_matrix(model, test_sentence, test_label, ax=ax, cmap=plt.cm.Blues)
    plt.title(f"{model_name} Confusion Matrix")
    plt.show()

visualize_model(model_naive_bayes, 'Naive Bayes')

ModuleNotFoundError: No module named 'matplotlib'

In [28]:
class BuildModel():

    def __init__(self,train_sentence,train_label,test_sentence,test_label,algo) -> None:
        self.train_sentence = train_sentence
        self.train_label = train_label
        self.test_sentence = test_sentence
        self.test_label = test_label
        self.algo = algo

    
    def run(self):
        self.build_model()
        self.score()
        return self.calculate_results()

    def build_model(self):
        self.model = Pipeline([
            ('tfidf', TfidfVectorizer()),
            ('algo',algo)
        ])
        return self.model.fit(self.train_sentence,train_label)
    
    def score(self):
        return self.model.score(test_sentence,test_label)

    def calculate_results(self):
        y_true = test_label
        y_pred = self.model.predict(test_sentence)
        model_accuracy = accuracy_score(y_true,y_pred) *100
        precision,recall,f1,_ = precision_recall_fscore_support(y_true,y_pred,average='weighted')
        model_result = {
            'accuracy':model_accuracy,
            'precision':precision,
            'recall':recall,
            'f1':f1
        }
        return model_result

        

In [29]:


# naive_bayes_model_run = BuildModel(train_sentence,train_label,test_sentence,test_label,algo=MultinomialNB())
# naive_bayes_model_run.run()

NameError: name 'algo' is not defined

In [30]:
from sklearn.ensemble import RandomForestClassifier

svc = BuildModel(train_sentence,train_label,test_sentence,test_label,algo=RandomForestClassifier())
svc.run()

NameError: name 'algo' is not defined

In [31]:
# Building Neural Network 
import keras as ks
from keras import layers,Model

input = layers.Input(shape=(1,), dtype="string")
x = text_vectorized(input)
x = embedding(x)
x = layers.GlobalAveragePooling1D()(x)
output = layers.Dense(1, activation="sigmoid")(x)
nn_model = Model(input,output)

In [32]:
nn_model.compile(loss='binary_crossentropy',optimizer="Adam",metrics=['accuracy'])

In [33]:
nn_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 11)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 11, 128)           1280000   
                                                                 
 global_average_pooling1d (G  (None, 128)              0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
Non-train

In [34]:
nn_history = nn_model.fit(train_sentence,train_label, epochs=5, )

Epoch 1/5
96/96 [==============================] - 4s 29ms/step - loss: 0.6708 - accuracy: 0.6851
Epoch 2/5
96/96 [==============================] - 3s 28ms/step - loss: 0.5660 - accuracy: 0.8115
Epoch 3/5
96/96 [==============================] - 3s 28ms/step - loss: 0.4464 - accuracy: 0.8496
Epoch 4/5
96/96 [==============================] - 3s 28ms/step - loss: 0.3609 - accuracy: 0.8729
Epoch 5/5
96/96 [==============================] - 3s 27ms/step - loss: 0.3019 - accuracy: 0.8943


In [35]:

nn_pred = tf.squeeze(tf.round(nn_model.predict(test_sentence))) 

24/24 [==============================] - 0s 3ms/step


In [36]:
calculate_results(test_label,nn_pred)

{'accuracy': 77.42782152230971,
 'precision': 0.7768009181492118,
 'recall': 0.7742782152230971,
 'f1': 0.7735962055713774}

In [37]:
nn_model.save('models/nn_model')

INFO:tensorflow:Assets written to: models/nn_model/assets


INFO:tensorflow:Assets written to: models/nn_model/assets
